---
name: "ci"

on:
    pull_request: {}
    push:
        branches:
            - "main"

env:
    CI: true

jobs:
    ci:
        runs-on: "ubuntu-20.04"

        steps:
            - uses: "actions/checkout@v3"
            - uses: "pnpm/action-setup@v2.2.2"
              with:
                  version: "latest"
            - uses: "actions/setup-node@v3"
              with:
                  node-version-file: ".nvmrc"
                  cache: "pnpm"
            - uses: "shivammathur/setup-php@v2"
              with:
                  php-version: "7.4"
                  tools: "composer"
            - run: "make install"
            - run: "make lint"
            - run: "make test"
